export interface ItemPresupuesto {
  L?: number,
  M?: number,
  id?: any,
  nombre: string,
  qty: number,
  categoria: string,
  subcategoria: string,
  unidad: string,
  laborRate: number,
  materialRate?: number,
  equipmentRate: number,
  fecha: any,
  estLaborCosts?: number,
  estEquipment?: number,
  estMat?: number,
  estSubMarkup?: number,
  totals?: number,
}
