export interface ItemPresupuesto {
  L: number,
  M: number,
  id?: any,
  nombre: string,
  qty: number,
  categoria: string,
  subcategoria: string,
  unidad: string,
  laborRateBase: number,
  laborRate: number,
  materialRateBase: number,
  materialRate: number,
  equipmentRateBase: number,
  equipmentRate: number,
  productionRateBase: number,
  productionRate?: number,
  laborHours: number,
  fecha: any,
  estLaborCosts?: number,
  estEquipment?: number,
  estMat?: number,
  estMatCosts?: number,
  estSubMarkup?: number,
  totals?: number,
}
