export interface Presupuesto {
    id?: any,
    nombre?: any,
    tipo?: any,
    estatus?: any,
    laborGubernamental?: any,
    zipCode?: any,
    laborRate?: any,
    equipmentRate?: any,
    materialRate?: any,
    descripcion?: any,
    taxPercentage?: any,
    subcontractorMarkup?: any,
    estRes?: any,
    estComm?: any,
    basePrice?: any,
    contingencyPercentage?: any,
    contigencyAmount?: any,
    profitPercentage?: any,
    profitAmount?: any,
    customHourMultiplier?: any,
    overallConstructionCost?: any,
    totalProjectCost?: any,
    fecha: any,
    idUsuario?: any,
}
